name: bar_client
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.4
  retrofit: ^4.4.1
  go_router: ^14.2.8
  json_serializable: ^6.8.0
  get_it: ^8.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12


flutter:
  uses-material-design: true
  assets:
    - lib/assets/
